import React, { useState } from 'react';
import { createRoot } from 'react-dom/client';
import { BrowserRouter, Link, Route, Routes } from 'react-router-dom';
import { QueryClient, QueryClientProvider, useQuery } from '@tanstack/react-query';
import './styles.css';

const api = import.meta.env.VITE_API_BASE_URL || '/api';
const request = (path: string, init: RequestInit = {}) => {
  const key = sessionStorage.getItem('adminApiKey');
  return fetch(api + path, { ...init, headers: { 'Content-Type': 'application/json', ...(key ? { Authorization: `Bearer ${key}` } : {}) } }).then(async r => {
    if (!r.ok) throw new Error(`${r.status}: ${await r.text()}`);
    return r.status === 204 ? null : r.json();
  });
};
const get = (path: string) => request(path);
function Header() { return <header><Link to="/">Job Collector</Link><nav><Link to="/jobs">공고</Link><Link to="/crawl-runs">수집 실행</Link><Link to="/sources">출처</Link><Link to="/profiles">프로필</Link><Link to="/api-tester">API 테스트</Link><Link to="/settings">설정</Link></nav></header>; }
function Overview() { const { data, error } = useQuery({ queryKey: ['summary'], queryFn: () => get('/v1/dashboard/summary') }); if (error) return <p>API 연결 오류</p>; const j = data?.jobs; return <><h1>개요</h1><section className="cards">{[['전체 공고', j?.total], ['활성 공고', j?.active], ['최근 7일 신규', j?.new_last_7_days], ['상태 확인 불가', j?.unknown]].map(([n, v]) => <article key={String(n)}><small>{n}</small><strong>{v ?? '-'}</strong></article>)}</section></>; }
function Jobs() { const [q, setQ] = useState(''); const [region, setRegion] = useState(''); const [experience, setExperience] = useState(''); const [employment, setEmployment] = useState(''); const [minYears, setMinYears] = useState(''); const { data, isLoading } = useQuery({ queryKey: ['jobs', q, region, experience, employment, minYears], queryFn: () => { const params = new URLSearchParams({ statuses: 'ACTIVE', keyword: q }); if (region) params.set('region', region); if (experience) params.set('experience_types', experience); if (employment) params.set('employment_types', employment); if (minYears) params.set('min_experience', minYears); return get(`/v1/jobs?${params}`); } }); return <><h1>공고</h1><section className="job-filters"><input placeholder="회사 또는 포지션 검색" value={q} onChange={e => setQ(e.target.value)} /><input placeholder="지역 (예: 경기)" value={region} onChange={e => setRegion(e.target.value)} /><select value={experience} onChange={e => setExperience(e.target.value)}><option value="">신입·경력 전체</option><option value="NEWBIE">신입</option><option value="EXPERIENCED">경력</option><option value="ANY">신입·경력</option></select><select value={employment} onChange={e => setEmployment(e.target.value)}><option value="">고용 형태 전체</option><option value="정규직">정규직</option><option value="계약직">계약직</option><option value="인턴">인턴</option></select><input type="number" min="0" placeholder="최소 경력(년)" value={minYears} onChange={e => setMinYears(e.target.value)} /></section>{isLoading ? <p>불러오는 중…</p> : <table><thead><tr><th>회사</th><th>포지션</th><th>출처</th><th>상태</th><th>지역</th><th>경력</th><th>고용 형태</th></tr></thead><tbody>{data?.items.map((x: any) => <tr key={x.id}><td>{x.company_name}</td><td><a href={x.url} target="_blank">{x.title}</a></td><td>{x.source}</td><td><span className={'badge ' + x.effective_status}>{x.effective_status}</span></td><td>{x.region || x.location_raw || '-'}</td><td>{x.experience.type} {x.experience.raw || '-'}</td><td>{x.employment_type || '-'}</td></tr>)}</tbody></table>}</>; }
function Simple({ path, title }: { path: string; title: string }) { const { data } = useQuery({ queryKey: [path], queryFn: () => get(path) }); return <><h1>{title}</h1><pre>{JSON.stringify(data, null, 2)}</pre></>; }
type Profile = { id: string; display_name: string; queries: string[]; include_keywords: string[]; exclude_keywords: string[]; source_queries: Record<string, string[]> };
const blank: Profile = { id: '', display_name: '', queries: [], include_keywords: [], exclude_keywords: [], source_queries: { WANTED: [] } };
const lines = (value: string) => value.split('\n').map(x => x.trim()).filter(Boolean);
function Profiles() {
  const { data, error, refetch } = useQuery<{ items: Profile[] }>({ queryKey: ['profiles'], queryFn: () => get('/v1/profiles') });
  const [form, setForm] = useState<Profile>(blank); const [editing, setEditing] = useState(false); const [message, setMessage] = useState('');
  const field = (name: keyof Profile) => Array.isArray(form[name]) ? (form[name] as string[]).join('\n') : '';
  const setLines = (name: keyof Profile, value: string) => setForm({ ...form, [name]: lines(value) });
  const save = async () => { try { await request(editing ? `/v1/admin/profiles/${form.id}` : '/v1/admin/profiles', { method: editing ? 'PUT' : 'POST', body: JSON.stringify(form) }); setMessage('저장되었습니다.'); setForm(blank); setEditing(false); refetch(); } catch (e) { setMessage(`저장 실패: ${String(e)}`); } };
  const remove = async (p: Profile) => { if (!confirm(`${p.display_name} 프로필을 삭제할까요?`)) return; try { await request(`/v1/admin/profiles/${p.id}`, { method: 'DELETE' }); refetch(); } catch (e) { setMessage(`삭제 실패: ${String(e)}`); } };
  return <><h1>검색 프로필</h1><p>관리자 API 키를 설정한 뒤 프로필을 추가·수정·삭제할 수 있습니다.</p>{error && <p>프로필을 불러올 수 없습니다.</p>}<section className="profile-grid">{data?.items.map(p => <article key={p.id}><strong>{p.display_name}</strong><small>{p.id}</small><p>{p.queries.join(', ')}</p><button onClick={() => { setForm(p); setEditing(true); }}>수정</button><button className="danger" onClick={() => remove(p)}>삭제</button></article>)}</section><h2>{editing ? '프로필 수정' : '프로필 추가'}</h2><section className="profile-form"><input placeholder="ID (예: automotive_security)" value={form.id} disabled={editing} onChange={e => setForm({ ...form, id: e.target.value })} /><input placeholder="표시 이름" value={form.display_name} onChange={e => setForm({ ...form, display_name: e.target.value })} /><label>검색어 (한 줄에 하나)<textarea value={field('queries')} onChange={e => setLines('queries', e.target.value)} /></label><label>포함 키워드 (한 줄에 하나)<textarea value={field('include_keywords')} onChange={e => setLines('include_keywords', e.target.value)} /></label><label>제외 키워드 (한 줄에 하나)<textarea value={field('exclude_keywords')} onChange={e => setLines('exclude_keywords', e.target.value)} /></label><label>원티드 전용 검색어 (한 줄에 하나)<textarea value={(form.source_queries.WANTED || []).join('\n')} onChange={e => setForm({ ...form, source_queries: { ...form.source_queries, WANTED: lines(e.target.value) } })} /></label><button onClick={save} disabled={!form.id || !form.display_name || !form.queries.length}>저장</button>{editing && <button onClick={() => { setEditing(false); setForm(blank); }}>취소</button>}<p>{message}</p></section></>;
}
type ApiEndpoint = { name: string; method: 'GET' | 'POST' | 'PUT' | 'DELETE'; path: string; body?: string; admin?: boolean };
const endpoints: ApiEndpoint[] = [
  { name: '프로세스 상태', method: 'GET', path: '/health' }, { name: '준비 상태', method: 'GET', path: '/ready' },
  { name: '공고 목록', method: 'GET', path: '/v1/jobs?statuses=ACTIVE&limit=20' }, { name: '공고 상세', method: 'GET', path: '/v1/jobs/{job_id}' },
  { name: '공고 변경 이력', method: 'GET', path: '/v1/jobs/{job_id}/changes' }, { name: '출처 목록', method: 'GET', path: '/v1/sources' },
  { name: '프로필 목록', method: 'GET', path: '/v1/profiles' }, { name: '프로필 상세', method: 'GET', path: '/v1/profiles/{profile_id}' },
  { name: '대시보드 요약', method: 'GET', path: '/v1/dashboard/summary' }, { name: '전체 동기화', method: 'POST', path: '/v1/admin/sync', body: '{\n  "profile": "mobility_sdv_security_cpp",\n  "mode": "incremental"\n}', admin: true },
  { name: '출처 동기화', method: 'POST', path: '/v1/admin/sources/WANTED/sync', body: '{\n  "profile": "mobility_sdv_security_cpp",\n  "mode": "incremental"\n}', admin: true },
  { name: '프로필 다시 로드', method: 'POST', path: '/v1/admin/profiles/reload', body: '{}', admin: true },
  { name: '수집 일정 조회', method: 'GET', path: '/v1/admin/settings/schedule', admin: true },
  { name: '수집 일정 저장', method: 'PUT', path: '/v1/admin/settings/schedule', body: '{\n  "sync_cron": "0 2 * * *",\n  "recheck_cron": "0 3 * * *"\n}', admin: true },
  { name: '전체 공고 삭제', method: 'DELETE', path: '/v1/admin/jobs', body: '{\n  "confirm": "DELETE_ALL"\n}', admin: true },
  { name: '수집 실행 목록', method: 'GET', path: '/v1/admin/crawl-runs', admin: true }, { name: '수집 실행 상세', method: 'GET', path: '/v1/admin/crawl-runs/{run_id}', admin: true },
];
function ApiTester() {
  const [selected, setSelected] = useState(0); const [path, setPath] = useState(endpoints[0].path); const [body, setBody] = useState(endpoints[0].body || '');
  const [result, setResult] = useState('아직 요청하지 않았습니다.'); const [loading, setLoading] = useState(false);
  const choose = (index: number) => { setSelected(index); setPath(endpoints[index].path); setBody(endpoints[index].body || ''); setResult('아직 요청하지 않았습니다.'); };
  const run = async () => { const endpoint = endpoints[selected]; if (path.includes('{')) { setResult('경로의 {job_id}, {profile_id}, {run_id}를 실제 값으로 바꿔주세요.'); return; } if (endpoint.admin && !sessionStorage.getItem('adminApiKey')) { setResult('관리자 API 키가 없습니다. 설정 화면에서 먼저 저장하세요.'); return; } try { setLoading(true); const started = performance.now(); const direct = path === '/health' || path === '/ready'; const url = direct && api.startsWith('http') ? `${new URL(api).origin}${path}` : direct ? path : api + path; const response = await fetch(url, { method: endpoint.method, headers: { 'Content-Type': 'application/json', ...(endpoint.admin ? { Authorization: `Bearer ${sessionStorage.getItem('adminApiKey')}` } : {}) }, ...(endpoint.method === 'GET' || endpoint.method === 'DELETE' ? {} : { body }) }); const text = await response.text(); const elapsed = Math.round(performance.now() - started); let output: unknown = text; try { output = text ? JSON.parse(text) : null; } catch { /* retain text */ } setResult(JSON.stringify({ status: response.status, ok: response.ok, duration_ms: elapsed, response: output }, null, 2)); } catch (error) { setResult(JSON.stringify({ error: String(error) }, null, 2)); } finally { setLoading(false); } };
  return <><h1>API 테스트</h1><p>등록된 API를 선택하고 실행 결과를 확인합니다. 관리자 API는 설정에 저장한 세션 키를 사용하며, 동기화 요청은 실제 수집을 시작합니다.</p><section className="api-tester"><label>API 선택<select value={selected} onChange={e => choose(Number(e.target.value))}>{endpoints.map((item, index) => <option key={item.name} value={index}>{item.method} · {item.name}{item.admin ? ' (관리자)' : ''}</option>)}</select></label><label>경로<input value={path} onChange={e => setPath(e.target.value)} /></label>{endpoints[selected].method !== 'GET' && <label>JSON 요청 본문<textarea value={body} onChange={e => setBody(e.target.value)} /></label>}<button onClick={run} disabled={loading}>{loading ? '요청 중…' : `${endpoints[selected].method} 요청 실행`}</button><h2>결과</h2><pre className="api-result">{result}</pre></section></>;
}
function Settings() { const [key, setKey] = useState(sessionStorage.getItem('adminApiKey') || ''); const [syncCron, setSyncCron] = useState('0 2 * * *'); const [recheckCron, setRecheckCron] = useState('0 3 * * *'); const [confirmText, setConfirmText] = useState(''); const [message, setMessage] = useState(''); const saveKey = () => { sessionStorage.setItem('adminApiKey', key); setMessage('관리자 API 키를 저장했습니다.'); }; const loadSchedule = async () => { try { const data = await request('/v1/admin/settings/schedule'); setSyncCron(data.sync_cron); setRecheckCron(data.recheck_cron); setMessage('현재 일정을 불러왔습니다.'); } catch (error) { setMessage(`일정 조회 실패: ${String(error)}`); } }; const saveSchedule = async () => { try { await request('/v1/admin/settings/schedule', { method: 'PUT', body: JSON.stringify({ sync_cron: syncCron, recheck_cron: recheckCron }) }); setMessage('일정을 저장했습니다. Scheduler는 최대 30초 안에 새 설정을 반영합니다.'); } catch (error) { setMessage(`일정 저장 실패: ${String(error)}`); } }; const deleteAll = async () => { if (confirmText !== 'DELETE_ALL') return; try { const data = await request('/v1/admin/jobs', { method: 'DELETE', body: JSON.stringify({ confirm: 'DELETE_ALL' }) }); setConfirmText(''); setMessage(`공고 ${data.deleted_jobs}개와 변경 이력 ${data.deleted_snapshots}개를 삭제했습니다.`); } catch (error) { setMessage(`전체 삭제 실패: ${String(error)}`); } }; return <><h1>설정</h1><section className="settings-card"><h2>관리자 인증</h2><p>관리자 API 키는 이 브라우저 세션에만 저장됩니다.</p><input type="password" value={key} onChange={e => setKey(e.target.value)} placeholder="관리자 API 키" /><button onClick={saveKey}>키 저장</button></section><section className="settings-card"><h2>수집 일정</h2><p>Cron 형식: 분 시 일 월 요일. 예: <code>0 2 * * *</code>는 매일 02:00입니다.</p><label>검색 프로필 동기화<input value={syncCron} onChange={e => setSyncCron(e.target.value)} /></label><label>기존 공고 재확인<input value={recheckCron} onChange={e => setRecheckCron(e.target.value)} /></label><button onClick={loadSchedule}>현재 일정 불러오기</button><button onClick={saveSchedule}>일정 저장</button></section><section className="settings-card danger-zone"><h2>수집 공고 전체 삭제</h2><p>공고와 변경 이력만 삭제합니다. 수집 실행 이력과 프로필은 유지됩니다. 계속하려면 정확히 <code>DELETE_ALL</code>을 입력하세요.</p><input value={confirmText} onChange={e => setConfirmText(e.target.value)} placeholder="DELETE_ALL" /><button className="danger" onClick={deleteAll} disabled={confirmText !== 'DELETE_ALL'}>공고 전체 삭제</button></section><p>{message}</p></>; }
function App() { return <><Header /><main><Routes><Route path="/" element={<Overview />} /><Route path="/jobs" element={<Jobs />} /><Route path="/crawl-runs" element={<Simple title="수집 실행" path="/v1/admin/crawl-runs" />} /><Route path="/sources" element={<Simple title="출처" path="/v1/sources" />} /><Route path="/profiles" element={<Profiles />} /><Route path="/api-tester" element={<ApiTester />} /><Route path="/settings" element={<Settings />} /></Routes></main></>; }
createRoot(document.getElementById('root')!).render(<React.StrictMode><QueryClientProvider client={new QueryClient()}><BrowserRouter><App /></BrowserRouter></QueryClientProvider></React.StrictMode>);
